export const URL_API = 'http://10.113.128.91:3000/api/'


/** LOGIN  **/
export const AUTH_REQUETE_ACTION = "AUTH_REQUETE_ACTION"; 
export const AUTH_SUCCES_ACTION = "AUTH_SUCCES_ACTION"; 
export const AUTH_FAILED_ACTION = "AUTH_FAILED_ACTION";
export const AUTH_SAVE_STATE_ACTION = "AUTH_SAVE_STATE_ACTION";
export const AUTH_REQUETE_SAVE_STATE_ACTION = "AUTH_REQUETE_SAVE_STATE_ACTION";
export const AUTH_CLEAR_STATE_ACTION = "AUTH_CLEAR_STATE_ACTION";
