export const URL_API = "http://192.168.1.16:3000/api/"


/** LOGIN  **/
export const AUTH_REQUETE_ACTION = "AUTH_REQUETE_ACTION"; 
export const AUTH_SUCCES_ACTION = "AUTH_SUCCES_ACTION"; 
export const AUTH_FAILED_ACTION = "AUTH_FAILED_ACTION";
export const AUTH_SAVE_STATE_ACTION = "AUTH_SAVE_STATE_ACTION";
export const AUTH_REQUETE_SAVE_STATE_ACTION = "AUTH_REQUETE_SAVE_STATE_ACTION";
export const AUTH_CLEAR_STATE_ACTION = "AUTH_CLEAR_STATE_ACTION";
